# Generated by Django 5.2.17 on 2026-09-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_child_due_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bmi",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-date", "-id"],
                "verbose_name": "BMI",
                "verbose_name_plural": "BMI",
            },
        ),
        migrations.AlterModelOptions(
            name="feeding",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-start"],
                "permissions": [
                    ("can_edit_feeding_settings", "Can edit Feeding settings")
                ],
                "verbose_name": "Feeding",
                "verbose_name_plural": "Feedings",
            },
        ),
        migrations.AlterModelOptions(
            name="headcircumference",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-date", "-id"],
                "verbose_name": "Head Circumference",
                "verbose_name_plural": "Head Circumference",
            },
        ),
        migrations.AlterModelOptions(
            name="height",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-date", "-id"],
                "verbose_name": "Height",
                "verbose_name_plural": "Height",
            },
        ),
        migrations.AlterModelOptions(
            name="weight",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-date", "-id"],
                "verbose_name": "Weight",
                "verbose_name_plural": "Weight",
            },
        ),
        migrations.AddField(
            model_name="feeding",
            name="breast_milk_amount",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Breast milk amount"
            ),
        ),
        migrations.AddField(
            model_name="feeding",
            name="formula_amount",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Formula amount"
            ),
        ),
        migrations.AlterField(
            model_name="feeding",
            name="type",
            field=models.CharField(
                choices=[
                    ("breast milk", "Breast milk"),
                    ("formula", "Formula"),
                    ("fortified breast milk", "Fortified breast milk"),
                    ("mixed", "Mixed"),
                    ("solid food", "Solid food"),
                ],
                max_length=255,
                verbose_name="Type",
            ),
        ),
    ]
